/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

/**
 *
 * @author jesus
 */

public class NewJFrame extends javax.swing.JFrame {
public static int totalD=0;
public static int totalM=0;
public static int totalM50=0;
public static int totalD50=0;
public static int totalM100=0;
public static int totalD100=0;
public static int totalM200=0;
public static int totalD200=0;
public static int totalM500=0;
public static int totalD500=0;
public static int totalM1000=0;
public static int totalD1000=0;


    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        totaldinero.setEnabled(false);
        totalmonedas.setEnabled(false);
        cantidadmonedas50.setEnabled(false);
        cantidadmonedas100.setEnabled(false);
        cantidadmonedas200.setEnabled(false);
        cantidadmonedas500.setEnabled(false);
        cantidadmonedas1000.setEnabled(false);
        cantidaddinero50.setEnabled(false);
        cantidaddinero100.setEnabled(false);
        cantidaddinero200.setEnabled(false);
        cantidaddinero500.setEnabled(false);
        cantidaddinero1000.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        totaldinero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        totalmonedas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        boton50 = new javax.swing.JButton();
        boton100 = new javax.swing.JButton();
        boton200 = new javax.swing.JButton();
        boton500 = new javax.swing.JButton();
        boton1000 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cantidadmonedas50 = new javax.swing.JTextField();
        cantidadmonedas100 = new javax.swing.JTextField();
        cantidadmonedas200 = new javax.swing.JTextField();
        cantidadmonedas500 = new javax.swing.JTextField();
        cantidadmonedas1000 = new javax.swing.JTextField();
        cantidaddinero50 = new javax.swing.JTextField();
        cantidaddinero100 = new javax.swing.JTextField();
        cantidaddinero200 = new javax.swing.JTextField();
        cantidaddinero500 = new javax.swing.JTextField();
        cantidaddinero1000 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Alcancia");

        jLabel2.setText("Total reunido");

        jLabel3.setText("Total monedas");

        jLabel4.setText("Agregar moneda");

        boton50.setText("50");
        boton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton50ActionPerformed(evt);
            }
        });

        boton100.setText("100");
        boton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton100ActionPerformed(evt);
            }
        });

        boton200.setText("200");
        boton200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton200ActionPerformed(evt);
            }
        });

        boton500.setText("500");
        boton500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton500ActionPerformed(evt);
            }
        });

        boton1000.setText("1000");
        boton1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1000ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cantidad de monedas por denominación");

        jLabel6.setText("Cantidad de dinero por denominación");

        cantidaddinero500.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totaldinero, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(199, 199, 199)
                                .addComponent(jLabel4))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cantidadmonedas50, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(boton50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cantidaddinero50, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadmonedas100, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidaddinero100, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cantidadmonedas200, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(cantidaddinero200, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadmonedas500, javax.swing.GroupLayout.PREFERRED_SIZE, 55, Short.MAX_VALUE)
                                    .addComponent(cantidaddinero500, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cantidadmonedas1000, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cantidaddinero1000, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton100, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton200, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton500, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton1000, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 40, Short.MAX_VALUE)))))
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(totaldinero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(totalmonedas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton50)
                    .addComponent(boton100)
                    .addComponent(boton200)
                    .addComponent(boton500)
                    .addComponent(boton1000))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cantidadmonedas50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadmonedas100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadmonedas200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadmonedas500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidadmonedas1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cantidaddinero50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidaddinero100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidaddinero200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidaddinero500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantidaddinero1000, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(169, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton100ActionPerformed
        totalD += 100;
        totalM++;
        totalM100++;
        totalD100 += 100;
        totaldinero.setText(totalD + "");
        totalmonedas.setText(totalM + "");
        cantidadmonedas100.setText(totalM100 + "");
        cantidaddinero100.setText(totalD100 + "");
       
    }//GEN-LAST:event_boton100ActionPerformed

    private void boton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton50ActionPerformed
       
        totalD += 50;
      totalM++;
      totalM50++;
      totalD50 += 50;
      totaldinero.setText(totalD + "");
      totalmonedas.setText(totalM + "");
      cantidadmonedas50.setText(totalM50 + "");
      cantidaddinero50.setText(totalD50 + "");
    }//GEN-LAST:event_boton50ActionPerformed

    private void boton200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton200ActionPerformed
          totalD += 200;
        totalM++;
        totalM200++;
        totalD200 += 200;
        totaldinero.setText(totalD + "");
        totalmonedas.setText(totalM + "");
        cantidadmonedas200.setText(totalM200 + "");
        cantidaddinero200.setText(totalD200 + "");
    }//GEN-LAST:event_boton200ActionPerformed

    private void boton500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton500ActionPerformed
          totalD += 500;
        totalM++;
        totalM500++;
        totalD500 += 500;
        totaldinero.setText(totalD + "");
        totalmonedas.setText(totalM + "");
        cantidadmonedas500.setText(totalM500 + "");
        cantidaddinero500.setText(totalD500 + "");
    }//GEN-LAST:event_boton500ActionPerformed

    private void boton1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1000ActionPerformed
          totalD += 1000;
        totalM++;
        totalM1000++;
        totalD1000 += 1000;
        totaldinero.setText(totalD + "");
        totalmonedas.setText(totalM + "");
        cantidadmonedas1000.setText(totalM1000 + "");
        cantidaddinero1000.setText(totalD1000 + "");
    }//GEN-LAST:event_boton1000ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                                  
        
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton100;
    private javax.swing.JButton boton1000;
    private javax.swing.JButton boton200;
    private javax.swing.JButton boton50;
    private javax.swing.JButton boton500;
    private javax.swing.JTextField cantidaddinero100;
    private javax.swing.JTextField cantidaddinero1000;
    private javax.swing.JTextField cantidaddinero200;
    private javax.swing.JTextField cantidaddinero50;
    private javax.swing.JTextField cantidaddinero500;
    private javax.swing.JTextField cantidadmonedas100;
    private javax.swing.JTextField cantidadmonedas1000;
    private javax.swing.JTextField cantidadmonedas200;
    private javax.swing.JTextField cantidadmonedas50;
    private javax.swing.JTextField cantidadmonedas500;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField totaldinero;
    private javax.swing.JTextField totalmonedas;
    // End of variables declaration//GEN-END:variables
}
